name: rss-to-twitter

on:
  schedule:
    # everyday at 01:00 UTC (10:00 JST)
    - cron: '0 1 * * *'

jobs:
  twitter:
    runs-on: ubuntu-latest
    steps:
      - uses: azu/rss-to-twitter@v2
        with:
          # RSS feed URL
          RSS_URL: "https://utelecon.adm.u-tokyo.ac.jp/notice/rss.xml"
          # UPDATE_WITHIN_MINUTES is calculated from cron schedule to be 1 day
          TWEET_TEMPLATE: '%title% %url%'
          TWITTER_APIKEY: ${{ secrets.TWITTER_APIKEY }}
          TWITTER_APIKEY_SECRET: ${{ secrets.TWITTER_APIKEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  twitter-en:
    runs-on: ubuntu-latest
    steps:
      - uses: azu/rss-to-twitter@v2
        with:
          # RSS feed URL
          RSS_URL: "https://utelecon.adm.u-tokyo.ac.jp/en/notice/rss.xml"
          # UPDATE_WITHIN_MINUTES is calculated from cron schedule to be 1 day
          TWEET_TEMPLATE: '%title% %url%'
          TWITTER_APIKEY: ${{ secrets.TWITTER_EN_APIKEY }}
          TWITTER_APIKEY_SECRET: ${{ secrets.TWITTER_EN_APIKEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_EN_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_EN_ACCESS_TOKEN_SECRET }}
